steps:
  - id: 'Build-Dataflow-Image'
    name: 'gcr.io/kaniko-project/executor:latest'
    waitFor: ['-']
    args:
    - --dockerfile=./Dockerfile
    - --destination=${_LOCATION}-docker.pkg.dev/explorede-390910/${_ARTIFACT_REPOSITORY}/${_SERVICE_TAG}:latest
    - --destination=${_LOCATION}-docker.pkg.dev/explorede-390910/${_ARTIFACT_REPOSITORY}/${_SERVICE_TAG}:${_TAG}
    - --cache=true
    - --cache-ttl=48h

  - id: "Build-template"
    name: "gcr.io/cloud-builders/gcloud"
    waitFor: ['Build-Dataflow-Image']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project explorede-390910
        gcloud dataflow flex-template build "gs://explorede-390910/flex-templates/batch/${_SERVICE_TAG}/latest.json" --image "${_LOCATION}-docker.pkg.dev/explorede-390910/${_ARTIFACT_REPOSITORY}/${_SERVICE_TAG}:${_TAG}" --sdk-language "PYTHON"
    timeout: 1800s

substitutions:
  _LOCATION: europe-west1
  _ARTIFACT_REPOSITORY: learning

timeout: '3600s'
tags: ['${_TAG}', 'build', '${_SERVICE_TAG}']

options:
  logging: CLOUD_LOGGING_ONLY
