steps:
  - id: 'Build-Image'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    waitFor: ['-']
    args:
      - '-c'
      - |
        gcloud config set builds/use_kaniko True
        gcloud builds submit -t gcr.io/explorede-390910/dataflows-batch:latest .
        gcloud container images add-tag gcr.io/explorede-390910/dataflows-batch:latest
        gcr.io/explorede-390910/dataflows-batch:latest

  - id: "Build-template"
    name: "gcr.io/cloud-builders/gcloud"
    waitFor: ['Build-Image']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project explorede-390910
        gcloud dataflow flex-template build "gs://explorede-390910/flex-templates/batch/one/latest.json" --image "gcr.io/explorede-390910/dataflows/batch/second:latest" --sdk-language "PYTHON"
    timeout: 1800s

timeout: '3500s'
tags: ['${_TAG}', 'build', '${_SERVICE_TAG}']

options:
  logging: CLOUD_LOGGING_ONLY